name: Publish Python Package

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build twine

    - name: Build package
      run: python -m build

    - name: Check PyPI token
      run: |
        if [ -z "${{ secrets.PYPI_API_TOKEN }}" ]; then
          echo "❌ PYPI_API_TOKEN is not set"
          exit 1
        fi
        echo "✅ PYPI_API_TOKEN is set"
        echo "Token starts with: ${PYPI_API_TOKEN:0:10}..."

    - name: Publish to TestPyPI
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.TEST_PYPI_API_TOKEN }}
      run: |
        if [ -n "${{ secrets.TEST_PYPI_API_TOKEN }}" ]; then
          echo "Publishing to TestPyPI..."
          twine upload --repository testpypi dist/* --verbose
        else
          echo "Skipping TestPyPI (no token set)"
        fi

    - name: Publish to PyPI
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
      run: |
        echo "Publishing to PyPI..."
        echo "Using token starting with: ${TWINE_PASSWORD:0:10}..."
        twine upload dist/* --verbose
